### ISSUE TITLE
Requirements and version of pytorch

### ISSUE THREAD

**Issue by izaskr** [sIncerass/prag_generation#6]
I'm using pytorch 1.5.0 and get the following error when running
`python run_experiment.py my_train.yaml`

I suspect this is due to the wrong version of pytorch, but I don' find a list of requirements.

> Traceback (most recent call last):
  File "run_experiment.py", line 82, in <module>
    run(config_d)
  File "run_experiment.py", line 42, in run
    trainer.training_start(model, data)
  File "/local/home/CE/skr/prag_generation/e2e-incre/components/trainer/__init__.py", line 107, in training_start
    train_loss = self.train_epoch(epoch_idx, model, train_batches)
  File "/local/home/CE/skr/prag_generation/e2e-incre/components/trainer/__init__.py", line 169, in train_epoch
    loss_data = loss_var.data[0]
IndexError: invalid index of a 0-dim tensor. Use `tensor.item()` in Python or `tensor.item<T>()` in C++ to convert a 0-dim tensor to a number

Thanks for the help!

**Comment by izaskr** [comment]
I've installed the correct versions of packages. For future users:

- torch 0.4.1 for CUDA 10 (within a conda env)
- pyaml, matplotlib, progressbar, progressbar2 (all with pip)

**Comment by izaskr** [comment]
I've installed the correct versions of packages. For future users:

- torch 0.4.1 for CUDA 10 (within a conda env)
- pyaml, matplotlib, progressbar, progressbar2 (all with pip)

**Comment by fp674018495** [comment]
l think  you can make  " loss_data = loss_var.data[0] "  as   "loss_data = float(loss_var)" ;
